name: test_project
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore_platform_interface: ^7.0.1
  firebase_rules: ^0.0.0
  firebase_rules_convert: ^0.0.0
  meta: ^1.16.0

dev_dependencies:
  rexios_lints: ^17.0.0

dependency_overrides:
  firebase_rules:
    path: ../firebase_rules
  firebase_rules_convert:
    path: ../firebase_rules_convert
