name: firebase_rules_linter
description: A linter for the firebase_rules package to prevent common issues
version: 0.2.0
homepage: https://github.com/IO-Design-Team/firebase_rules/tree/master/firebase_rules_linter

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.7
  analysis_server_plugin: ^0.3.3
  collection: ^1.16.0
  source_helper: ^1.3.4
  source_gen: ^4.0.2
  meta: ^1.17.0

dev_dependencies:
  rexios_lints: ^17.0.0
  analyzer_testing: ^0.1.2
  test_reflective_loader: ^0.4.0
