name: firebase_rules_convert
description: A bridge to bring cloud_firestore_platform_interface types into firebase_rules
version: 0.1.3
homepage: https://github.com/IO-Design-Team/firebase_rules/tree/master/firebase_rules_convert

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  firebase_rules: ^0.2.0
  cloud_firestore_platform_interface: ^7.0.0

dev_dependencies:
  rexios_lints: ^17.0.0
